services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: flightuser
      POSTGRES_PASSWORD: flightpassword
      POSTGRES_DB: flightdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  producer:
    container_name: producer
    build:
      context: ./services/producer
    environment:
      - KAFKA_BROKER=kafka:29092
    env_file:
      - ./.env
    depends_on:
      - kafka

  enricher:
    container_name: enricher
    build:
      context: ./services/enricher
    environment:
      - KAFKA_BROKER=kafka:29092
    depends_on:
      - kafka

  storage:
    container_name: storage
    build:
      context: ./services/storage
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=db
      - DB_NAME=flightdb
      - DB_USER=flightuser
      - DB_PASSWORD=flightpassword
    depends_on:
      - kafka
      - db

volumes:
  postgres-data:
